name: carousel
description: A Flutter Carousel.
version: 0.1.0
author: Gabriel Valério <gbrvalerio@gmail.com>
homepage: https://github.com/gbrvalerio/carousel

dependencies:
  flutter:
    sdk: flutter

environment:
  sdk: ">=1.23.0<=2.1.0"

dev_dependencies:
  test: ^0.12.0
